name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - name: Lint test
        run: flutter analyze
      - run: flutter test
      - run: flutter config --enable-web
      - run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
